name: Weekly check all Markdown links

on:
  schedule:
    - cron: "0 12 * * 4"

# Remove all permissions from GITHUB_TOKEN except metadata.
permissions: {}

jobs:
  markdown-link-check:
    name: Broken Links
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # tag=v3.5.2
      - uses: gaurav-nelson/github-action-markdown-link-check@5c5dfc0ac2e225883c0e5f03a85311ec2830d368 # tag=v1
        with:
          use-quiet-mode: 'yes'
          config-file: .markdownlinkcheck.json
