name: scan-images

on:
  schedule:
    - cron: "0 12 * * 1"

# Remove all permissions from GITHUB_TOKEN except metadata.
permissions: {}

jobs:
  scan:
    strategy:
      matrix:
        branch: [ main, release-1.3, release-1.2 ]
    name: Trivy
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # tag=v3.3.0
      with:
        ref: ${{ matrix.branch }}
    - name: Setup go
      uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # tag=v3.4.0
      with:
        go-version: 1.19
    - name: Run verify container script
      run: make verify-container-images